### ISSUE TITLE
Skip user when they have no client key 

### ISSUE THREAD

**Issue by cwjohnston** [hw-cookbooks/chef-server-populator#36]
In this example the client_key is empty:
```
"chef_server": {
   "client_key": "",
   "type": [ "user"],
   "orgs": {
     "myorg": {
       "enabled": true,
       "admin": true
     }
   }
}
```

Which causes an error from the `chef-server-ctl` command to fail the chef run.

**Comment by luckymike** [comment]
This must be a regression in the refactor I made to the client recipe, I'll work up a fix shortly.
