### ISSUE TITLE
Key not added for client/user in 12.1

### ISSUE THREAD

**Issue by yoshiwaan** [hw-cookbooks/chef-server-populator#43]
Hi,

The command for adding a key to a user or client has changed in 12.1 from earlier versions. The --public-key-path flag is now required, instead of simply adding an extra parameter.

On Amazon linux I also found that the new chef-server v4.0.0 cookbook doesn't work, although it may work fines for other distros. There were quite a few changes from 3.1.1 to 4.0.0 so the chef-server cookbook version might need locking for now if it introduces breaking changes.

https://github.com/hw-cookbooks/chef-server-populator/pull/42

I would really appreciate a quick merge for this as I discovered the problem while deploying our production Chef server >.<

Regards,
Yoshi

**Comment by yoshiwaan** [comment]
Any movement on this?

**Comment by yoshiwaan** [comment]
Checking in to see if this is in the pipeline

**Comment by luckymike** [comment]
I'm hoping to hit this tomorrow, but definitely this week. Thank you!

**Comment by luckymike** [comment]
I got lost in the tests and PRs for backups today. Those should be merged this evening, then I'm clear to work on this.

**Comment by luckymike** [comment]
@yoshiwaan you mention issues with the later chef server cookbook on amazon linux. Are those still a problem? I just decided not to pin to the old version, b/c the issues seemed to entirely be dependency naming, which should be solved at whatever level you resolve dependencies, but if there are other issues, I'm willing to pin back.

**Comment by yoshiwaan** [comment]
@luckymike Actually there were no issues from what I could see

Chef sent out a notice saying there were potentially going to be breaking changes with version 4 of the chef-server cookbook but nothing much came of it when I upgraded.

I did notice though in the test kitchen test suite that I had to change the chef server version string for centos boxes (I had to take off the .rhel extension).

**Comment by luckymike** [comment]
Running the final tests for this. It'll come this week!
