### ISSUE TITLE
Random password generation can fail

### ISSUE THREAD

**Issue by yoshiwaan** [hw-cookbooks/chef-server-populator#47]
'password' => item.fetch('password', SecureRandom.urlsafe_base64(23))

The above line is used to generate a password for a user if none is specified in a data bag item.
As the string is random it is possible the first character of this password can be a hyphen.
Because of the use case of this password (passing as a command line parameter) the hyphen beginning the string  can be interpreted as a switch parameter to the chef-server-ctl command and cause the chef run to fail.

Any leading hyphens should be stripped from the generated password string

**Comment by luckymike** [comment]
Nice catch! I can get that in when I handle the other stuff (hopefully tomorrow!)

**Comment by luckymike** [comment]
`.gsub(/^\-*/,'')` should do the trick here. Will include this in the next release!
