### ISSUE TITLE
Skipping organization creation

### ISSUE THREAD

**Issue by albsOps** [hw-cookbooks/chef-server-populator#60]
When using the cookbook, my organization was never created, in fact it was skipped.
The organization data bag has the parameter "enabled": "true.

Debugging the code I've found that changing true for "true" in the next line: https://github.com/hw-cookbooks/chef-server-populator/blob/master/recipes/client.rb#L33 was solving the issue.
I did not submit a pull requests because I am not sure if this is a bug.

**Comment by luckymike** [comment]
Your org data bag item should have `"enabled": true` as a boolean, not a string.
