### ISSUE TITLE
Update the admin.pem to pivotal.pem

### ISSUE THREAD

**Issue by adam-carbone** [hw-cookbooks/chef-server-populator#63]
I believe the current default uses 

/etc/opscode/pivotal.pem for the signing-key

So shouldn't the following be updated or at least add a comment so that people know for chef-server 12
default[:chef_server_populator][:user] = 'admin'
default[:chef_server_populator][:pem] = '/etc/chef-server/admin.pem'

**Comment by luckymike** [comment]
Hi @adam-carbone I'm not clear what you're suggesting here, can you elaborate on where you see the need for a change/update? Is this for the cookbook behavior or the documentation?

**Comment by adam-carbone** [comment]
Hi @luckymike I have been trying to get use the cookbook in conjunction with chef-provisioning / chef-zero. I keep having an issue with the cookbook telling me that it can't find "/etc/chef-server/admin.pem" that I told it to use for the signing key! so I started looking for it an I couldn't find it on the provisioned machine. Upon investigation it seemed like that changed in Chef 12 + to use the pivotal user. /etc/opscode/pivotal.pem. So I thought that the attribute needed to be updated... but I can't seem to get that to work either, so I might just be completely lost so feel free to close this out if you feel things are correct must have been my mistake! Just having a hard time to get this all to work together, although it seems like a great cookbook!

**Comment by luckymike** [comment]
Generally we provide a signing key out of band (see the examples or the test fixtures), so I'm not sure those defaults have ever actually been used against Chef 12.
