### ISSUE TITLE
Version evaluating to 0.0, causing the wrong commands to run

### ISSUE THREAD

**Issue by adam-carbone** [hw-cookbooks/chef-server-populator#64]
node['chef-server'][:version].to_f is used in the recipes to determine whether or not it is running in a chef server >= 12.1. This determines which commands are run when creating users, clients, organizations. I have an issue where the --public-key is not being passed in the command so the public key is not being used. 

I'm willing to do the work to fix the issue if you can point me in the direction as to where the node['chef-server'][:version] is being set! 

logging from inside the recipe 
Chef-version: 0.0
Add client key command 'chef-server-ctl add-client-key lmid acarbone-dev /var/chef/cache/acarbone-dev.pub --key-name populator'

**Comment by luckymike** [comment]
Hi @adam-carbone, that attribute has no default (unless the chef-server cookbook imposes one, but I doubt it). It's possible that the recipe logic is flipped for the nil case, which would give you latest (i.e. should behave like > 12.1. We'd love a PR with an additional test suite for this case.

Thanks!

**Comment by adam-carbone** [comment]
I have looked into is more and the cookbook chef-server sets that value to nil that then gets passed to the chef_ingredient and interpreted as :latest. 
I'm looking into how I could figure out what chef_ingredient  resolved for the version when :latest is used. If I can sort that out without to much trouble I will certainly try to put together a PR! 

Do you normally specify the version when you run the recipe?

**Comment by luckymike** [comment]
Latest should always be > 12.1, so I don't think there's any need to decipher which version is installed if the version isn't specified.

**Comment by adam-carbone** [comment]
but it uses an attribute in the client recipe that isn't set 

if node['chef-server']['version'].to_f >= 12.1

node['chef-server']['version'] is set to nil so it evaluates to 0.0 and thus ends up using the wrong command!

**Comment by adam-carbone** [comment]
so would you be ok to changing that to recipe to something like  

if (node['chef-server']['version'].nil?) || ( node['chef-server']['version'].to_f >= 12.1)

**Comment by jonattta** [comment]
I noticed exactly the same @adam-carbone , chef-version 0.0 which results in the wrong pub key command, looking forward for a fix.

**Comment by luckymike** [comment]
Thanks for the bump @jonattta, I seem to have missed @adam-carbone's last comment. I believe I've duplicated this issue, and I should have a fix ready shortly!

**Comment by adam-carbone** [comment]
That is great news, I had largely re-written the internals to get around
this but I will definitely check it out again.



Senior Managing Partner
Village Rock Investment Group, LLC
www.villagerockinvestments.com
adam.carbone@villagerockinvestments.com
(774) 260-2011

www.linkedin.com/in/adamjcarbone
www.facebook.com/adam.j.carbone.1
twitter.com/AdamCarbone

*Building a brighter future for America one family at a time!*


*add contact
<https://sites.google.com/a/villagerockinvestments.com/contacts/vcf/adam-carbone.vcf?attredirects=0&d=1>*

This email and any files transmitted with it are confidential information
and is intended only for the individual or entity to whom they are addressed.
If you are not the named addressee, you should not disseminate, distribute
or copy this email. Please notify the sender immediately by email if you
have received this email by mistake and delete this email from your system.
Email transmission cannot be guaranteed to be secure or error-free, as
information could be intercepted, corrupted, lost, destroyed, arrive late
or incomplete, or contain viruses. The sender, therefore, does not accept
liability for any errors or omissions in the contents of this message which
arise as a result of email transmission. If verification is required,
please request a hard-copy version. Please note that any views or opinions
presented in this email are solely those of the author and do not
necessarily represent those of the organization.


On Tue, May 10, 2016 at 12:13 PM, Cameron Johnston <notifications@github.com
