### ISSUE TITLE
Chef provisioning support?

### ISSUE THREAD

**Issue by tatemz** [hw-cookbooks/chef-server-populator#71]
In lieu of jtimberman's and John Kiesner's talks at last year's Chef conferences, do you have any intention of turning this repo towards using the chef provisioning model such as is found in the the [example repo](https://github.com/chef-cookbooks/chef-reference)?

**Comment by luckymike** [comment]
Hi @tatemz, I think these are apples and oranges. This cookbook specifically populates a chef server with users/orgs/clients. It is unopinionated about how the server is provisioned (though we strongly prefer [SparkleFormation](http://www.sparkleformation.io/) for such things). 

Without digging into the example repo you've linked, I would assume that you could use a chef-provisioning recipe to run this cookbook.

If there's a specific function that you think is missing from this cookbook, I'd be happy to have a look if you can point it out.

Thanks!
