### ISSUE TITLE
Invalid only_if check in client.rb recipe for add org validator key

### ISSUE THREAD

**Issue by yoshiwaan** [hw-cookbooks/chef-server-populator#9]
Hi,

The only_if guard in the client.rb recipe on line 81 is a syntax error. It should be wrapped in {}.
Currently this generates an error as it tries to execute a bash command with the same name as the value of the pub_key variable.

**Comment by yoshiwaan** [comment]
There's also an error in the guards for checking key existence. I've created a pull request for these fixes.
I also updated the readme a little as it wasn't obvious what format to put the public keys in.

Note that I did not increase the metadata version value and the pull request is to go into your develop branch so that it can go through whatever testing process you have.

The changes work in an amazon linux 2015.03 server I have, but that's as much testing as I've done.

https://github.com/hw-cookbooks/chef-server-populator/pull/10

**Comment by luckymike** [comment]
Thanks! The key existence update appears to have introduced a regression with older versions of chef 12 where the output definitely uses `key_name` (I just confirmed in 12.0.5). I'm guessing someone decided to shorten it in a later release, and am confirming currently. I'll be updating to just check for `name <foo>` instead of `^name <foo>` which should catch both outputs.

**Comment by luckymike** [comment]
@yoshiwaan I can't reproduce an error with `^key_name` in 12.0.7 either, which version did you have the issue with?

**Comment by yoshiwaan** [comment]
Oops. I thought I did that, must have missed the caret character. That was definitely my intention.

I have this currently:
```
 chef-server-core.x86_64              12.0.8-1.el6                 @chef_stable_
```
which uses the 12.0.3 gem.

```
[root@ip-172-28-7-210 ~]# chef-server-ctl list-client-keys indochino indochino-validator

name: populator
expired: false
```

**Comment by luckymike** [comment]
I've fixed it here: #16. Will have my client recipe adjustments done today or tomorrow, I hope.

**Comment by yoshiwaan** [comment]
Great, thanks for the quick work.

**Comment by luckymike** [comment]
@yoshiwaan, we're prepping a release today. You can see the latest here: https://github.com/hw-cookbooks/chef-server-populator/tree/develop

**Comment by luckymike** [comment]
Just released these updates in version 1.1.0. This also includes updates to the backup and restore recipes for full Chef 12 support! Thanks for your help!

**Comment by yoshiwaan** [comment]
Thanks Mike. I'll wait until the bug in Chef Server is fixed in the next release and redeploy our Chef server.

**Comment by yoshiwaan** [comment]
Okay, aside from the bug with Chef Server that's still around (there's been no new release yet) this works well.

I found one other bug which I raised as an issue.

Thanks
